server:
  port: 8080

logging:
  level:
    root: INFO
    com.example.demo: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 