spring:
  datasource:
    url: jdbc:h2:mem:devdb
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: DEBUG
    com.example.demo: TRACE 